services:
  - type: web
    name: unitribe-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn unitribe_server.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: unitribe_server.settings
